
.PHONY: all
all:
	../sh/buildall.sh


.PHONY: kernel
kernel:
	../sh/build_kernel.sh


.PHONY: app
app:
	../sh/build_app.sh


.PHONY: run
run:
	../sh/buildall.sh && ../sh/run.sh


.PHONY: qemu
qemu:
	../sh/run.sh


.PHONY: clean
clean:
	../sh/clean.sh




