
.PHONY: all
all:
	../sh/buildall.sh


.PHONY: kernel
kernel:
	../sh/build.sh kernel


.PHONY: run
run:
	../sh/buildall.sh && ../sh/run.sh



.PHONY: qemu
qemu:
	../sh/run.sh



.PHONY: clean
clean:
	../sh/build.sh clean


